### ISSUE TITLE
Allow download font when clicking the button

### ISSUE THREAD

**Issue by marcianosr** [etunni/Arapey-Minisite#13]

**Comment by RoelN** [comment]
Note: the down arrow suggest we'll scroll to a part of this site, as opposed to opening a new tab with Github. So let's add a simple section somewhere near the bottom, which can just say "Download Arapey here" which links to Github.

**Comment by RoelN** [comment]
Addressed in b3e8496b587f0b7fd802f605deed5d405d49905d
