### ISSUE TITLE
Improvements to "sliding wall of letters"

### ISSUE THREAD

**Issue by marcianosr** [etunni/Arapey-Minisite#15]
Still some imperfections left, but merging this so we can move along. In a future PR, we should address:

- Performance/prevention of layout thrashing
- ~Refactor code to JS object~
- ~Fix bug where "mousedown" sticks after doing a mouseup outside the viewport~ FIXED
- ~Touch support~ FIXED
- ~Cross browser testing~ FIXED

**Comment by RoelN** [comment]
Closing this, handling performance in separate issue
